import os
import pandas as pd
import glob


configfile: "config/config.yaml"


# Hacky attempt to make conda work
os.environ["PATH"] = os.environ["PATH"] + os.pathsep + config["path_to_conda"]
# os.environ["PATH"] = config["path_to_conda"] + os.pathsep + os.environ["PATH"]


include: "rules/common.smk"
include: "rules/meta.smk"
include: "rules/cage.smk"
include: "rules/cerberus.smk"
include: "rules/flair.smk"
include: "rules/isotools.smk"
include: "rules/isoquant.smk"
include: "rules/lapa.smk"
include: "rules/kallisto.smk"
include: "rules/minimap2.smk"
include: "rules/rnaseq.smk"
include: "rules/sqanti.smk"
include: "rules/star.smk"
include: "rules/stringtie.smk"
include: "rules/talon.smk"


rule all:
    input:
        expand("results/{tool}/transcriptome/{tissue}_sorted.gtf.gz", tool=WORKING_TOOLS, tissue=util.tissues),
        expand("results/{tool}/transcriptome/{tissue}_sorted.gtf.gz.tbi", tool=WORKING_TOOLS, tissue=util.tissues),
        expand("results/sqanti/{tool}/qc/{tissue}/{tissue}_SQANTI3_report.html", tool=WORKING_TOOLS, tissue=util.tissues),
        "results/plots/upset/all/mean.png",
        "results/plots/upset/filtered/mean.png",
        "results/meta/dag.pdf",
