import os
import pandas as pd
import glob

configfile: "config/config.yaml"

# Hacky attempt to make conda work
os.environ["PATH"]= config["path_to_conda"] + os.pathsep + os.environ["PATH"]

include: "rules/common.smk"
include: "rules/preprocessing.smk"
include: "rules/cage.smk"
include: "rules/cerberus.smk"
include: "rules/flair.smk"
include: "rules/isotools.smk"
include: "rules/lapa.smk"
include: "rules/talon.smk"
include: "rules/sqanti.smk"

rule all:
    input:
        "output/plot.png"
