# Directory paths
reads_dir: /path/to/data/reads
alignment_dir: /path/to/data/alignment_v45
annot_gtf: /path/to/data/gencode_human/version_45/gencode.v45.annotation.gtf.gz
# GENCODE or Ensembl
annot_source: GENCODE
genome_fa: /path/to/data/gencode_human/version_45/GRCh38.p14.genome.fa
genome_name: GRCh38
annot_name: gencode_v45
sequencing_platform: Sequel II

sample_table: /path/to/data/reads/metadata_tissue.tsv
# tsv file with sample ID matching the IDs above and the file path to the transcriptome in .gtf.gz format
transcriptome_table: /path/to/data/talon_gtf/gtf_metadata.tsv

# If true input files to talon will be copied to $TMPDIR before running talon
# Useful if IO is slow
talon_use_tmpdir: true

# cluster couldn't find conda
path_to_conda: /home/lankenau/miniforge3/bin

# Searched for CAGE files matching the tissues from the sample table
# File name needs to contain the tissue name
CAGE_dir: /path/to/data/CAGE

# aggregating all samples with cerberus at once can be memory intensive
# set to None to disable
aggregate_at_once_limit: 5
