# GENCODE or Ensembl
annot_source: GENCODE
genome_name: GRCh38
annot_name: gencode_v46
sequencing_platform: Sequel II

annot_gtf: /project/hfa_work/ENCODE/data/gencode_human/version_46/gencode.v46.annotation.gtf.gz
# needs to be bgzf compressed and have a .tbi index
annot_gff: /project/hfa_work/ENCODE/data/gencode_human/version_46/gencode.v46.annotation_sorted.gff3.gz
annot_fa: /project/hfa_work/ENCODE/data/gencode_human/version_46/gencode.v46.transcripts.fa.gz
reference_fa: /project/hfa_work/ENCODE/data/gencode_human/version_46/GRCh38.p14.genome.fa

# additional columns are allowed and ignored for all of these
# tsv file with "sample ID", "group" and "file"
sample_table: /project/hfa_work/ENCODE/data/reads/metadata_tissue.tsv
# tsv file with "sample ID" matching the IDs above and the path in the "file" column
rnaseq_fofn:
  fastq: /project/hfa_work/ENCODE/data/rna_seq/fastq/rnaseq_metadata_fastq.tsv
  bam: /project/hfa_work/ENCODE/data/rna_seq/bam/rnaseq_metadata_bam.tsv
  kallisto: /project/hfa_work/ENCODE/data/rna_seq/kallisto/rnaseq_metadata_kallisto.tsv
# One .bed.gz file per tissue is expected, file names need to contain the tissue name as specified in the sample table
CAGE_dir: /project/hfa_work/ENCODE/data/CAGE
# Download bed file from https://polyasite.unibas.ch/atlas#2
PolyASitePeaks: /project/hfa_work/ENCODE/data/PolyA_Site/atlas.clusters.2.0.GRCh38.96.bed.gz

isotools:
  coverage_threshold: 0
  query: "BALANCED"

stringtie:
  # Stringtie needs manual building with make, the path to the binary is needed
  path: /project/hfa_work/ENCODE/code/stringtie/stringtie

talon:
  # If true, input files to talon will be copied to $TMPDIR before running talon, useful if IO is slow
  use_tmpdir: true

star:
  # Extra options for STAR
  index:
    extra: ""
  align:
    # Same options as SQANTI3 would use (very close to default ENCODE options)
    extra: "--alignSJoverhangMin 8 --alignSJDBoverhangMin 1 --outFilterType BySJout --outSAMunmapped Within --outFilterMultimapNmax 20 --outFilterMismatchNoverLmax 0.04 --outFilterMismatchNmax 999 --alignIntronMin 20 --alignIntronMax 1000000 --alignMatesGapMax 1000000 --sjdbScore 1 --twopassMode Basic"

sqanti:
  # Path to the SQANTI3 repo
  path: /project/hfa_work/ENCODE/code/SQANTI3
  # Download polyA motif list from SQANTI repo or link your own
  polyA_motif_list: "/project/hfa_work/ENCODE/code/SQANTI3/data/polyA_motifs/mouse_and_human.polyA_motif.txt"
  # see https://github.com/ConesaLab/SQANTI3/wiki/Running-SQANTI3-Quality-Control#arguments-and-parameters-in-sqanti3-qc for options
  extra: "--ratio_TSS_metric mean"

cerberus:
  # aggregating all samples with cerberus at once can be memory intensive
  # set to None to disable
  aggregate_at_once_limit: 5

# cluster couldn't find conda
path_to_conda: /home/lankenau/miniforge-pypy3/bin

# Reduces bam and gtf files to chr15 for testing
test_run: True
# Replace resources from above, when test_run is set to True
test_config:
  sample_table: /project/hfa_work/ENCODE/data/reads/metadata_tissue_test.tsv
  CAGE_dir: /project/hfa_work/ENCODE/data/CAGE_test
  rnaseq_fofn:
    fastq: /project/hfa_work/ENCODE/data/rna_seq/fastq_test/rnaseq_metadata_fastq_test.tsv
    bam: /project/hfa_work/ENCODE/data/rna_seq/bam/rnaseq_metadata_bam.tsv
  annot_gtf: /project/hfa_work/ENCODE/data/gencode_human/version_46/gencode.v46.annotation.chr15.gtf.gz
